trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
    name: 'DEFRA-TRD'
    
steps:

  - task: DotNetCoreCLI@2
    displayName: Restore for $(BuildConfiguration)
    inputs:
      command: restore
      projects: '**/Defra.Trade.ReMos.AssuranceService.Tests.csproj'
      feedsToUse: 'config'
      includeNuGetOrg: true
      nugetConfigPath: 'nuget.config'


  - task: DotNetCoreCLI@2
    displayName: publish for $(BuildConfiguration)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/Defra.Trade.ReMos.AssuranceService.Tests.csproj'
      arguments: --no-restore --configuration $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)


  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
