trigger: none

parameters:
  - name: branchName
    type: string
    default: 'refs/heads/dev'
  - name: Environment
    type: string
    default: 'tst'
  - name: ApiEndpoint
    type: string
    default: 'dev'
  - name: SeleniumGrid
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: DeviceName
    type: string
    default: 'Windows'
  - name: BSOSVersion
    type: string
    default: '11'
  - name: Target
    type: string
    default: 'Edge'

schedules:
- cron: "0 4 * * Mon,Tue,Wed,Thu,Fri"
  displayName: Daily midnight build
  branches:
    include:
    - dev
    exclude:
    - feature/*
    - task/*
    - master
    

resources:
  repositories:
    - repository: clientautomationreponew
      type: github
      name: DEFRA/nirms-exports-signup-service-automation
      ref: refs/heads/dev
      endpoint: 

stages:
  
  - stage: EnvironmentCheck
    displayName: EnvironmentCheck
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: EnvironmentCheck
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ''  
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        targetBrowserName: ${{parameters.Target}}
        dependsOn: ''
        
  - stage: SmokeTest
    displayName: SmokeTest
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: SmokeTest
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: '' 
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        targetBrowserName: ${{parameters.Target}}
        dependsOn: 'EnvironmentCheck'
