trigger: none

parameters:
  - name: branchName
    type: string
    default: 'refs/heads/dev'
  - name: Environment
    type: string
    default: 'tst'
  - name: ApiEndpoint
    type: string
    default: 'dev'
  - name: SeleniumGrid
    type: string
    default: 'https://hub.browserstack.com/wd/hub/'
  - name: DeviceName
    type: string
    default: 'Windows'
  - name: BSOSVersion
    type: string
    default: '11'
  - name: Target
    type: string
    default: 'Edge'

 
resources:
  repositories:
    - repository: clientautomationreponew
      type: git
      name: DEFRA-NI-GENERAL-CERTIFICATE/Defra.Trade.ReMos.AssuranceService.Automation
      ref: $(Build.SourceBranch)

stages:
  
  - stage: EnvironmentCheck
    displayName: EnvironmentCheck
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: EnvironmentCheck
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: ''  
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        targetBrowserName: ${{parameters.Target}}
        dependsOn: ''
        
  - stage: RunOnlyScenarios
    displayName: RunOnlyScenarios
    jobs:
    - template: run-test-template.yml
      parameters:
        jobName: RunOnlyScenarios
        envConfigParam: ${{ parameters.Environment}}
        apiEndPoint: ${{ parameters.ApiEndpoint}}
        branchName: ${{ parameters.branchName}}
        SeleniumGrid: '' 
        DeviceName: ${{parameters.DeviceName}}
        BSOSVersion: ${{parameters.BSOSVersion}}
        targetBrowserName: ${{parameters.Target}}
        dependsOn: 'EnvironmentCheck'
