parameters:
  - name: jobName
    type: string
  - name: envConfigParam
    type: string
  - name: apiEndPoint
    type: string
  - name: branchName
    type: string
  - name: SeleniumGrid
    type: string
  - name: DeviceName
    type: string
  - name: BSOSVersion
    type: string
  - name: dependsOn
    type: string

jobs: 

- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobName }}
  timeoutInMinutes: 300

  pool:
    name: 'DEFRA-TRD'

  variables:
    - template: test-variables_CI.yml
      parameters:
        env: ${{parameters.envConfigParam}}
        jobNameParam: ${{parameters.jobName}}

  steps:
    
    - task: DownloadBuildArtifacts@0
      displayName: TestArtifact
      inputs:
        buildType: 'specific'
        project: '303b7da1-1c89-467e-9730-12849c222832'
        pipeline: '3746'
        buildVersionToDownload: 'latestFromBranch'
        branchName: ${{ parameters.branchName }}
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy Test Artifacts'
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)/drop'
        TargetFolder: $(System.DefaultWorkingDirectory)
        OverWrite: true
        CleanTargetFolder: true
    
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '**/Defra.GC.UI.Tests.zip'
        destinationFolder: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests'
        cleanDestinationFolder: false
        overwriteExistingFiles: true
    
    - task: replacetokens@3
      displayName: Replace Tokens
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests'
        targetFiles: 'appsettings.json'
        encoding: auto
        writeBOM: true
        escapeType: json
        actionOnMissing: warn
        keepToken: false
        tokenPrefix: '#{{'
        tokenSuffix: '}}'
        useLegacyPattern: false
        enableTelemetry: false

    - powershell: |
        $jsonString = Get-Content "$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/appsettings.json" | Out-String
        Write-Host $jsonString
      displayName: 'Display appsettings.json'
    
    - powershell: |
        Set-Location -Path "$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests"
        dotnet test "$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/Defra.GC.UI.Tests.dll" --settings "$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/testrun.runsettings" --filter "$(Where)" --logger:"trx;logfilename=${{ parameters.jobName }}.xml"
      displayName: 'Execute Tests'
      failOnStderr: true
      ignoreLASTEXITCODE: true
      continueOnError: true
    
    - ${{ if or( eq(parameters.branchName, 'refs/heads/master'), contains(parameters.branchName, 'release'), eq(parameters.branchName, 'dev') ) }}:
      - task: SpecFlowPlus@0
        displayName: 'LivingDoc with FeatureFolder generatorSource'
        inputs:
          generatorSource: 'TestAssembly'
          testAssemblyFilePath: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/Defra.GC.UI.Tests.dll'
          testExecutionJson: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/TestExecution.json'
          projectName: 'Defra.Trade.ReMos.AssuranceService.Automation'
          projectLanguage: 'en'
          workItemPrefix: 'WI'
        enabled: true
        continueOnError: true
        condition: always()
        timeoutInMinutes: 10
    
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Screenshots'
      inputs:
          testResultsFiles: 'TestFailures*.png'
          artifactName: ${{ parameters.jobName }}
          targetPath: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/TestResults/'

    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      inputs:
        testResultsFormat: VSTest
        testResultsFiles: ${{ parameters.jobName }}.xml
        searchFolder: '$(System.DefaultWorkingDirectory)/Defra.GC.UI.Tests/TestResults/'
        testRunTitle: ${{ parameters.jobName }}
        failTaskOnFailedTests: true
